# SERVER
server:
  port: 8080 # Server HTTP port

# SPRING
spring:
  application:
    name: akuna-core # Application name
  data:
    jpa:
      uri: ${POSTGRES_URI:postgresql://localhost:27018/akuna}
#  sleuth:
#    enabled: ${ZIPKIN_ENABLED:false}
#    sampler:
#      percentage: 1
#  zipkin:
#      baseUrl: ${ZIPKIN_URL}
#      service.name: ${spring.application.name}

services:
  akuna-core:
    url: ${AKUNA_CORE_URL:}
  api-gateway:
    url: ${API_GATEWAY_URL:}

logging:
  level:
    org.springframework.web: ERROR
    com.akuna.core: DEBUG

---
# Secure configuration, when SPRING_PROFILES_ACTIVE = !dev
spring:
    profiles: "prod"
security:
  oauth2:
    client:
      access-token-uri: ${IDP_URL:""}/token
      client-id: ${IDP_CLIENT_ID:""}
      client-secret: ${IDP_CLIENT_SECRET:""}
      grant-type: client_credentials
    resource:
      tokenInfoUri: any
      identity-provider: mitre
      identity-provider-url: ${IDP_URL:""}
  ignored:
    /webjars/**,
    /swagger-ui.html,
    /swagger-resources/**,
    /v2/api-docs,
    /images/**,
    /error,
    /health,
    /heapdump

---
# Insecure configuration, when SPRING_PROFILES_ACTIVE = dev
spring:
    profiles: "dev"
security:
  ignored: /**